name: PickaxeUpgradesGUI
version: 1.0-T1
author: MrCoder_
website: fiverr.com/mrcoder_
main: me.mrcoder.pugui.Main
description: Commissioned by Rexie
api-version: 1.16
softdepend: [Vault]
commands:
  pugui:
    description: Info Command
    usage: /<command>
    aliases: [pickaxeupgradesgui]